# Generated by Django 4.0.3 on 2022-03-27 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0002_alter_compnay_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compnay',
            new_name='Company',
        ),
    ]
